modName=DynamicTreesTinkersConstruct
modId=dttconstruct
modVersion=1.5.1
group=com.maxhyper.dttconstruct

mcVersion=1.20.1
forgeVersion=47.3.0
mappingsVersion=2023.09.03

dynamicTreesVersion=1.4.5
dynamicTreesPlusVersion=1.2.1
patchouliVersion=1.20.1-84.1
suggestionProviderFixVersion=1.0.0
ccVersion=1.111.0

curseFileType=release

updateCheckerPath=Add-ons/TinkersConstruct.json
versionRecommended=true

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
