modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/DynamicTreesTeam/DynamicTrees-TinkersConstruct/issues"

[[mods]]
modId = "dttconstruct"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for Tinker's Construct"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/TinkersConstruct.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-tinkers-construct"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Tinker's Construct
'''

[[dependencies.dttconstruct]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dttconstruct]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dttconstruct]]
modId = "dynamictrees"
mandatory = true
versionRange = "[1.1.0-BETA7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dttconstruct]]
modId = "dynamictreesplus"
mandatory = false
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dttconstruct]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.8.0.0,)"
ordering = "AFTER"
side = "BOTH"